Repository w3c-lbd-cg/bot, pull requests merged in 2020-05, with the labels that each got.

#78 Patch issue36
  DERIROOMAlignment.ttl
  IFCOWL4_ADD2Alignment.ttl
Labels: enhancement

#61 Added Semantic Web Journal reference
  README.md
Labels: Revision of BOT Docs

#77 Patch issue75
  config.js
  index.html
Labels: Revision of BOT Docs, enhancement
